export const GET_PLAYLIST_DETAIL_REQUEST = 'PlaylistDetail/GET_PLAYLIST_DETAIL_REQUEST';
export const GET_PLAYLIST_DETAIL_SUCCESS = 'PlaylistDetail/GET_PLAYLIST_DETAIL_SUCCESS';
export const GET_PLAYLIST_DETAIL_FAILED = 'PlaylistDetail/GET_PLAYLIST_DETAIL_FAILED';
