// GET Playlist Detail
export const GET_PLAYLIST_DETAIL_REQUEST = 'PlaylistDetail/GET_PLAYLIST_DETAIL_REQUEST';
export const GET_PLAYLIST_DETAIL_SUCCESS = 'PlaylistDetail/GET_PLAYLIST_DETAIL_SUCCESS';
export const GET_PLAYLIST_DETAIL_FAILED = 'PlaylistDetail/GET_PLAYLIST_DETAIL_FAILED';

// DELETE Playlist Song
export const DELETE_PLAYLIST_SONG_REQUEST = 'PlaylistDetail/GET_PLAYLIST_SONG_REQUEST';
export const DELETE_PLAYLIST_SONG_SUCCESS = 'PlaylistDetail/GET_PLAYLIST_SONG_SUCCESS';
export const DELETE_PLAYLIST_SONG_FAILED = 'PlaylistDetail/GET_PLAYLIST_SONG_FAILED';
