export const GET_USER_DETAIL_REQUEST = 'Profile/GET_USER_DETAIL_REQUEST';
export const GET_USER_DETAIL_SUCCESS = 'Profile/GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAILED = 'Profile/GET_USER_DETAIL_FAILED';

export const PATCH_UPDATE_PROFILE_REQUEST = 'Profile/PATCH_UPDATE_PROFILE_REQUEST';
export const PATCH_UPDATE_PROFILE_SUCCESS = 'Profile/PATCH_UPDATE_PROFILE_SUCCESS';
export const PATCH_UPDATE_PROFILE_FAILED = 'Profile/PATCH_UPDATE_PROFILE_FAILED';
