export const POST_CREATE_PLAYLIST_REQUEST = 'CreatePlaylist/POST_CREATE_PLAYLIST_REQUEST';
export const POST_CREATE_PLAYLIST_SUCCESS = 'CreatePlaylist/POST_CREATE_PLAYLIST_SUCCESS';
export const POST_CREATE_PLAYLIST_FAILED = 'CreatePlaylist/POST_CREATE_PLAYLIST_FAILED';
