export const GET_SONG_DETAIL_REQUEST = 'Player/GET_SONG_DETAIL_REQUEST';
export const GET_SONG_DETAIL_SUCCESS = 'Player/GET_SONG_DETAIL_SUCCESS';
export const GET_SONG_DETAIL_FAILED = 'Player/GET_SONG_DETAIL_FAILED';
