export const GET_USER_LIST_REQUEST = 'Home/GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'Home/GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILED = 'Home/GET_USER_LIST_FAILED';

export const GET_PLAYLIST_LIST_REQUEST = 'Home/GET_PLAYLIST_LIST_REQUEST';
export const GET_PLAYLIST_LIST_SUCCESS = 'Home/GET_PLAYLIST_LIST_SUCCESS';
export const GET_PLAYLIST_LIST_FAILED = 'Home/GET_PLAYLIST_LIST_FAILED';

export const GET_SONG_LIST_REQUEST = 'Home/GET_SONG_LIST_REQUEST';
export const GET_SONG_LIST_SUCCESS = 'Home/GET_SONG_LIST_SUCCESS';
export const GET_SONG_LIST_FAILED = 'Home/GET_SONG_LIST_FAILED';

export const POST_ADD_PLAYLIST_SONG_REQUEST = 'Home/POST_ADD_PLAYLIST_SONG_REQUEST';
export const POST_ADD_PLAYLIST_SONG_SUCCESS = 'Home/POST_ADD_PLAYLIST_SONG_SUCCESS';
export const POST_ADD_PLAYLIST_SONG_FAILED = 'Home/POST_ADD_PLAYLIST_SONG_FAILED';
