export const POST_CREATE_SONG_REQUEST = 'CreateSong/POST_CREATE_SONG_REQUEST';
export const POST_CREATE_SONG_SUCCESS = 'CreateSong/POST_CREATE_SONG_SUCCESS';
export const POST_CREATE_SONG_FAILED = 'CreateSong/POST_CREATE_SONG_FAILED';
